import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const ralewaySans = Raleway({
  variable: "--font-ralewaySans-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ralewaySans.variable}  antialiased`}
      >
     <div className="px-8 mt-5">
     <Navbar/>
     </div>
        {children}
      </body>
    </html>
  );
}
